services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: petsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pets-service:
    build: ./pets-service
    container_name: pets-service
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/petsdb
      - FIREBASE_CREDENTIALS=/firebase-config/firebase-service-account.json
    volumes:
      - ./firebase-config:/firebase-config
    ports:
      - "8000:8000"
